name: Backend CI

on:
  push:
  pull_request:

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Docker versions
        run: |
          docker --version
          docker compose version

      - name: Prepare .env for compose
        run: |
          cp .env.example .env
          if grep -q '^HOST_DB_PORT=' .env; then
            sed -i 's/^HOST_DB_PORT=.*/HOST_DB_PORT=3307/' .env
          else
            echo 'HOST_DB_PORT=3307' >> .env
          fi

      - name: Build API image
        run: docker build -t estacionamento-web-backend-api .

      - name: Compose up (db + api)
        run: docker compose up -d db api

      - name: Wait for API health
        run: |
          for i in {1..40}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health || true)
            if [ "$code" = "200" ]; then
              echo "API healthy"; exit 0; fi
            sleep 3
          done
          echo "API not healthy"
          docker compose logs db api --tail=200 || true
          exit 1

      - name: Compose down
        if: always()
        run: docker compose down -v
